export const SET_BENEFITS = "SET_BENEFITS";
export const SET_HISTORY_BENEFITS = "SET_HISTORY_BENEFITS";
export const START_LOADING_BENEFITS = "START_LOADING_BENEFITS";
export const END_LOADING_BENEFITS = "END_LOADING_BENEFITS";
